In [77]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [78]:
df = pd.read_csv("K:\ML-Projects\Kodein\data1_test.csv")
df

Feature_1  Feature_2  Feature_3  Target
0     97.533783  88.329103  98.191966       0
1    102.838058  78.783627  90.867559       0
2     95.155724  86.679155  94.861119       0
3    102.838797  87.504581  99.622361       0
4     99.238078  86.704614  91.685225       0
..          ...        ...        ...     ...
195   95.944852  73.432026  77.215081       2
196   98.884384  75.145090  76.521510       2
197   94.958002  81.372707  77.798078       2
198  103.293445  75.642798  75.084644       2
199  106.345156  71.583643  68.666107       2

[200 rows x 4 columns]

In [79]:
df.isnull().sum()

Feature_1    0
Feature_2    0
Feature_3    0
Target       0
dtype: int64

In [80]:
df.Target.unique()

array([0, 1, 2], dtype=int64)

In [81]:
df.shape

(200, 4)

In [82]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

x= df.drop("Target",axis=1)
y=df.Target

scaler1 =StandardScaler()
scaler2 =MinMaxScaler()
x_scaled_1 = scaler1.fit_transform(x)
x_scaled_2=scaler2.fit_transform(x)



In [83]:
x_train_1,x_test_1,y_train_1,y_test_1 = train_test_split(x_scaled_1,y,test_size=0.2,random_state=42)
x_train_2,x_test_2,y_train_2,y_test_2 = train_test_split(x_scaled_2,y,test_size=0.2,random_state=42)

In [84]:
model1 = LogisticRegression()
model1.fit(x_train_2,y_train_2)


pred= model1.predict(x_test_2)
score =accuracy_score(pred,y_test_2)

In [85]:
score

0.95

In [86]:
df2 = pd.read_csv("K:\ML-Projects\Kodein\data1_test.csv")

df2

Feature_1  Feature_2  Feature_3  Target
0     97.533783  88.329103  98.191966       0
1    102.838058  78.783627  90.867559       0
2     95.155724  86.679155  94.861119       0
3    102.838797  87.504581  99.622361       0
4     99.238078  86.704614  91.685225       0
..          ...        ...        ...     ...
195   95.944852  73.432026  77.215081       2
196   98.884384  75.145090  76.521510       2
197   94.958002  81.372707  77.798078       2
198  103.293445  75.642798  75.084644       2
199  106.345156  71.583643  68.666107       2

[200 rows x 4 columns]

In [87]:
df2.shape

(200, 4)

In [88]:
df2_x= df.drop("Target",axis=1)
df2_y=df.Target

In [119]:
df2_x_scaled=scaler2.fit_transform(df2_x)

pred2=model1.predict(df2_x_scaled)
score2=accuracy_score(pred2,df2_y)

In [131]:
pred2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2], dtype=int64)

In [132]:
score2

0.97

Neural Network


In [160]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy
model2 = Sequential([
  Dense(units=64, activation='relu', input_shape=(x_scaled_1.shape[1],)),
  Dense(units=30, activation='relu'),
  Dense(units=3)
  ])

model2.compile(optimizer=Adam(),
              loss=SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])

model2.fit(x_train_2,y_train_2,epochs=500)

        



Epoch 1/500


c:\Users\harsh\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3228 - loss: 1.0762  
Epoch 2/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3636 - loss: 1.0514 
Epoch 3/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4202 - loss: 1.0312 
Epoch 4/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5235 - loss: 0.9971 
Epoch 5/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5345 - loss: 0.9830 
Epoch 6/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5695 - loss: 0.9544 
Epoch 7/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6253 - loss: 0.9333 
Epoch 8/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6358 - loss: 0.9291 
Epoch 9/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7939 - loss: 0.8904 
Epoch 10/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8059 - loss: 0.8630 
Epoch 11/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8305 - loss: 0.8351 
Epoch 12/500
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8655 - loss: 0.8020 


In [157]:
pred3 = model2.predict(df2_x_scaled)  
pred3_categorical = np.argmax(pred3, axis=1)  
score3 = accuracy_score(pred3_categorical, df2_y) 


7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


In [158]:
pred3_categorical

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2], dtype=int64)

In [159]:
score3

0.97